### ISSUE TITLE
Not working hls on server wowza

### ISSUE THREAD

**Issue by ROKAISAKKON** [videojs/videojs-contrib-hls#550]
Video.js 5.7.0
videojs-contrib-hls - v1.3.7
Chrome 48.0.2564.109
Wowza Streaming Engine 4 Monthly Edition 4.3.0 build16025

playlist.m3u8

```

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM
INF:BANDWIDTH=1035985,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=480x320
chunklist_w2044689982.m3u8

```

chunklist_w2044689982.m3u8

```

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:9.6,
media_w2044689982_0.ts
#EXTINF:9.6,
media_w2044689982_1.ts
#EXTINF:9.6,
media_w2044689982_2.ts
...
#EXTINF:9.6,
media_w2044689982_92.ts
#EXTINF:7.019,
media_w2044689982_93.ts
#EXT-X-ENDLIST

```

.ts files stop downloading but new .ts files keep coming

url test : http://122.155.184.12/video_stream/_definst_/OTV2/lakorn/48_d_one_tv/02_wiman/ep3/03_wiman_part1_320.mp4/playlist.m3u8

srorry, i'm not good english

**Comment by svenspielvogel** [comment]
I addressed this in my fork. The problem is, that wowza hls chunks seem to be too short, so the buffer misses some milliseconds. this results in a loop.
see https://github.com/mevango/videojs-contrib-hls

**Comment by svenspielvogel** [comment]
see https://github.com/videojs/videojs-contrib-hls/pull/561

**Comment by gak2** [comment]
Sven, I am experiencing exactly these issues live-streaming from Wowza: the browser seems to lose track of .ts files and just loops, loading the .m3u8 file.

I am very hopeful that your script might help, but - apologies for my inexperience - I'm have trouble applying it!  I am running 'video.js' from ZenCDN, and v.2.0.0 of 'videojs-contrib-hls.js' locally - all on a Windows server.  Could you please help me test your changes?  

I've tried replacing the latter file with yours from the 'src' folder on your fork, but it doesn't work.  Do I need more files from your fork?  Is non-Windows compilation required?  Even a working example would be great, just so I could follow the source code!

Thank you Sven ..

**Comment by gak2** [comment]
Sven, I used your code to replace the middle section of v1.3.11/videojs.hls.js.  It runs, but didn't fix the problem.  I'm pretty stuck, unsure whether the issue is HLS/Wowza/my code.  Any guidance / live streaming examples greatly appreciated!

Thanks!

**Comment by ROKAISAKKON** [comment]
@gak2 try v2.0.1  and video js last version 
https://github.com/videojs/videojs-contrib-hls/releases  

@svenspielvogel thank so much

**Comment by gak2** [comment]
@ROKAISAKKON Thank you so much for replying.  
But how do I do add @svenspielvogel 's code?  I am now using the following files:

- http://vjs.zencdn.net/5.9.2/video.js
- hls/v2.0.1/videojs-contrib-hls.js

So which file / files do I add from https://github.com/mevango/videojs-contrib-hls to replace "videojs-contrib-hls.js"?  Really appreciate your help with this.

Thank you again!

**Comment by svenspielvogel** [comment]
Hey @ROKAISAKKON , @gak2 ,

sorry for not replying yet.

Did you use my current fork? I merged 2.0.1 into it.

https://github.com/mevango/videojs-contrib-hls

after `npm install` you need to run `npm run build`.

Feel free to ask if it didn't build. I could provide you a dist then.

**Comment by gak2** [comment]
@svenspielvogel Hey, thanks for the reply!

I'm sure I'm doing something wrong here, but the command-line spinner just spins endlessly on `npm install`  :\  I'll keep working at it .. in the meantime, is there any way you could please provide a dist of the videojs-contrib-hls.js?

Thanks Sven!

**Comment by svenspielvogel** [comment]
@gak2 there you go
[videojs-contrib-hls.zip](https://github.com/videojs/videojs-contrib-hls/files/266077/videojs-contrib-hls.zip)

**Comment by gak2** [comment]
@svenspielvogel Thank you so much for this.  Your help is greatly appreciated.  I still can't get it to work however.  

First, Video.js throws an error: `(CODE:2 MEDIA_ERR_NETWORK) "A network error caused the media download to fail part-way."`

Then your file throws this error: `videojs-contrib-hls.js:11329 Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.`

Any thoughts on why this might be happening?  I've tried tweaking Wowza CupertinoStreaming setup, but no luck .. thank you Sven!

**Comment by svenspielvogel** [comment]
[videojs-contrib-hls-mevango.zip](https://github.com/videojs/videojs-contrib-hls/files/266216/videojs-contrib-hls-mevango.zip)

try this @gak2

**Comment by gak2** [comment]
@svenspielvogel Thanks for this!

I now get this error: 

`videojs-contrib-hls-mevango2.js:9668Uncaught TypeError: _this.player_.audioTracks is not a function`

And the stream does not improve:

```
media_w222106005_60.ts	
media_w222106005_61.ts	
media_w222106005_59.ts	
media_w222106005_60.ts	
media_w222106005_61.ts	
media_w222106005_59.ts	
media_w222106005_60.ts	
media_w222106005_61.ts	
media_w222106005_59.ts	
media_w222106005_60.ts	
media_w222106005_61.ts	
media_w222106005_59.ts	
media_w222106005_60.ts	
media_w222106005_61.ts	
chunklist_w222106005.m3u8	
chunklist_w222106005.m3u8	
chunklist_w222106005.m3u8	
chunklist_w222106005.m3u8	
chunklist_w222106005.m3u8	
chunklist_w222106005.m3u8
```

Any thoughts!?

Thanks Sven!

**Comment by ROKAISAKKON** [comment]
@gak2 try  https://github.com/videojs/videojs-contrib-hls/releases/download/v2.0.1/videojs-contrib-hls.min.js  and without modifying it

Work for me.

**Comment by gak2** [comment]
@ROKAISAKKON Thanks for this!  But I'm afraid my video stops after a few seconds.

Could you please send me your HTML?  So I can try to replicate your setup?

Thanks!

**Comment by ROKAISAKKON** [comment]
@gak2 try Video.js 5.7.0

**Comment by gak2** [comment]
Same problem on 5.7.0 @ROKAISAKKON  :(

It keeps jumping between two .ts files, then loops requesting the .m3u8 file.  

It must be something to do with the source video format: VOD works fine (eg. http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8), but this live stream from a Wowza server doesn't work.  It will stream OK through other players though, like VLC.  Have you any thoughts/experience on live Wowza streaming in the browser?

Thank you!

**Comment by ROKAISAKKON** [comment]
![image](https://cloud.githubusercontent.com/assets/9902370/15293842/f0e70368-1bb3-11e6-847e-5bd8de27715c.png)

It work!
Can you sent all file to me ?

**Comment by gak2** [comment]
Hi @ROKAISAKKON ,

Thanks for the response!  I have a lot of other code in the files re. other javascript libraries - for example wrapping the video around a sphere with three.js - so it's very messy and I'd need to tidy it up for you.

Other VOD streams do work fine with my code though - it's just this live Wowza stream that keeps breaking.  And even the live stream works in VLC player.  So I'm starting to think it may an incompatibility between videojs-hls and the keyframing/Wowza transcoding ..?

Could you possibly send a simple outline of your HTML markup?  At least then I could ensure I'm not making a silly mistake in my code!

Thanks again for your help.

**Comment by gak2** [comment]
Hello again @ROKAISAKKON !

My markup is now very simple, and these scripts work perfectly for VOD.  
However, they don't work for live video streamed over Wowza:

![image](https://cloud.githubusercontent.com/assets/259711/15357459/ec635aaa-1cf6-11e6-9796-869017faa55c.png)

Your thoughts/ideas would be greatly appreciated!

Thanks again ..

**Comment by gesinger** [comment]
Sorry this ticket has gone a long time without much attention. We've made a lot of changes to videojs-contrib-hls in the meantime, including a lot of changes around segment fetching logic.

Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output) and a sample stream?

Thank you for reporting the issue.

**Comment by gesinger** [comment]
This looks similar to: https://github.com/videojs/videojs-contrib-hls/issues/775 and https://github.com/videojs/videojs-contrib-hls/issues/982 .  Closing in favor of those. If this is a separate issue from those, and you are still experiencing this issue with the latest version of videojs-contrib-hls (as of this comment, v5.1.0), please re-open the issue and provide a reduced test case using [this template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.

**Comment by mikhoul** [comment]
@gesinger 

> Would you be able to give the latest version (as of this comment, v4.1.1) a shot? If it's still a problem, would you be able to provide a reduced test case using this template and a sample stream?


I'm new to Video.js and I tried to set-up a simple instance of video.js on Jsbin.com and with MP4 file npo problem but when I tried to use an M3U8 stream to test it,  I encountered problems... :disappointed: 

I was looking to find why it happen, if I do something "wrong" browsing the "Issues"  here and I found your template :smile_cat: 

So I tried my stream http://www.streambox.fr/playlists/test_001/stream.m3u8 in your template and the same problem happened sadly, at least I know now the problem was not because my vdeo.js instance had an error.

Could you help me to find why this error happen with this stream ?   Why the stream don't play but keep loading .ts files in the browser console ? 

The stream work fine on other players like mediaelement or VLC.  I tried it in Firefox and Chrome with the same result.


Regards :octocat:
